version: '3.3'

services:
  pwn-no-549:
    privileged: true
    build:
        context: .
    ports:
      - '13370:13370'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1000M  